/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Lead {
    paymentStatus: Status;
    pbStatus: Status;
    assignedAgent: AgentId;
    claimStatus: Status;
    policyStatus: Status;
    createdAt: Time;
    ncbPercent: bigint;
    mobileNumber: string;
    updatedAt: Time;
    kycStatus: Status;
    reminderCount: bigint;
    leadId: LeadId;
    rating: bigint;
    rcStatus: Status;
    quoteStatus: Status;
    ownerChange: boolean;
    premiumAmount: bigint;
}
export type UserId = Principal;
export type LeadId = bigint;
export type Time = bigint;
export type AgentId = Principal;
export interface User {
    principal: UserId;
    name: string;
    role: Role;
    email: string;
}
export enum Role {
    admin = "admin",
    agent = "agent"
}
export enum Status {
    pending = "pending",
    completed = "completed",
    inProgress = "inProgress"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(secret: string): Promise<void>;
    assignLead(leadId: LeadId, agentId: AgentId): Promise<void>;
    createLead(mobileNumber: string): Promise<LeadId>;
    createUser(principal: UserId, email: string, role: Role, name: string): Promise<void>;
    getAllLeads(): Promise<Array<Lead>>;
    getLead(leadId: LeadId): Promise<Lead>;
    getLeadsByAgent(agentId: AgentId): Promise<Array<Lead>>;
    getUser(principal: UserId): Promise<User>;
    updateLead(leadId: LeadId, lead: Lead): Promise<void>;
    updateLeadStatus(leadId: LeadId, status: Status): Promise<void>;
}
import type { AgentId as _AgentId, Lead as _Lead, LeadId as _LeadId, Role as _Role, Status as _Status, Time as _Time, User as _User, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async assignLead(arg0: LeadId, arg1: AgentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignLead(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignLead(arg0, arg1);
            return result;
        }
    }
    async createLead(arg0: string): Promise<LeadId> {
        if (this.processError) {
            try {
                const result = await this.actor.createLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLead(arg0);
            return result;
        }
    }
    async createUser(arg0: UserId, arg1: string, arg2: Role, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, arg1, to_candid_Role_n1(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, arg1, to_candid_Role_n1(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async getAllLeads(): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLeads();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLeads();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLead(arg0: LeadId): Promise<Lead> {
        if (this.processError) {
            try {
                const result = await this.actor.getLead(arg0);
                return from_candid_Lead_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLead(arg0);
            return from_candid_Lead_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadsByAgent(arg0: AgentId): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadsByAgent(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadsByAgent(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUser(arg0: UserId): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_User_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_User_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateLead(arg0: LeadId, arg1: Lead): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLead(arg0, to_candid_Lead_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLead(arg0, to_candid_Lead_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateLeadStatus(arg0: LeadId, arg1: Status): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLeadStatus(arg0, to_candid_Status_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLeadStatus(arg0, to_candid_Status_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async _initializeAccessControlWithSecret(_secret: string): Promise<void> {
        // No-op: access control not used in this project
        return Promise.resolve();
    }
}
function from_candid_Lead_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lead): Lead {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_User_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentStatus: _Status;
    pbStatus: _Status;
    assignedAgent: _AgentId;
    claimStatus: _Status;
    policyStatus: _Status;
    createdAt: _Time;
    ncbPercent: bigint;
    mobileNumber: string;
    updatedAt: _Time;
    kycStatus: _Status;
    reminderCount: bigint;
    leadId: _LeadId;
    rating: bigint;
    rcStatus: _Status;
    quoteStatus: _Status;
    ownerChange: boolean;
    premiumAmount: bigint;
}): {
    paymentStatus: Status;
    pbStatus: Status;
    assignedAgent: AgentId;
    claimStatus: Status;
    policyStatus: Status;
    createdAt: Time;
    ncbPercent: bigint;
    mobileNumber: string;
    updatedAt: Time;
    kycStatus: Status;
    reminderCount: bigint;
    leadId: LeadId;
    rating: bigint;
    rcStatus: Status;
    quoteStatus: Status;
    ownerChange: boolean;
    premiumAmount: bigint;
} {
    return {
        paymentStatus: from_candid_Status_n6(_uploadFile, _downloadFile, value.paymentStatus),
        pbStatus: from_candid_Status_n6(_uploadFile, _downloadFile, value.pbStatus),
        assignedAgent: value.assignedAgent,
        claimStatus: from_candid_Status_n6(_uploadFile, _downloadFile, value.claimStatus),
        policyStatus: from_candid_Status_n6(_uploadFile, _downloadFile, value.policyStatus),
        createdAt: value.createdAt,
        ncbPercent: value.ncbPercent,
        mobileNumber: value.mobileNumber,
        updatedAt: value.updatedAt,
        kycStatus: from_candid_Status_n6(_uploadFile, _downloadFile, value.kycStatus),
        reminderCount: value.reminderCount,
        leadId: value.leadId,
        rating: value.rating,
        rcStatus: from_candid_Status_n6(_uploadFile, _downloadFile, value.rcStatus),
        quoteStatus: from_candid_Status_n6(_uploadFile, _downloadFile, value.quoteStatus),
        ownerChange: value.ownerChange,
        premiumAmount: value.premiumAmount
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: _UserId;
    name: string;
    role: _Role;
    email: string;
}): {
    principal: UserId;
    name: string;
    role: Role;
    email: string;
} {
    return {
        principal: value.principal,
        name: value.name,
        role: from_candid_Role_n10(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    agent: null;
}): Role {
    return "admin" in value ? Role.admin : "agent" in value ? Role.agent : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): Status {
    return "pending" in value ? Status.pending : "completed" in value ? Status.completed : "inProgress" in value ? Status.inProgress : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Lead>): Array<Lead> {
    return value.map((x)=>from_candid_Lead_n4(_uploadFile, _downloadFile, x));
}
function to_candid_Lead_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Lead): _Lead {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentStatus: Status;
    pbStatus: Status;
    assignedAgent: AgentId;
    claimStatus: Status;
    policyStatus: Status;
    createdAt: Time;
    ncbPercent: bigint;
    mobileNumber: string;
    updatedAt: Time;
    kycStatus: Status;
    reminderCount: bigint;
    leadId: LeadId;
    rating: bigint;
    rcStatus: Status;
    quoteStatus: Status;
    ownerChange: boolean;
    premiumAmount: bigint;
}): {
    paymentStatus: _Status;
    pbStatus: _Status;
    assignedAgent: _AgentId;
    claimStatus: _Status;
    policyStatus: _Status;
    createdAt: _Time;
    ncbPercent: bigint;
    mobileNumber: string;
    updatedAt: _Time;
    kycStatus: _Status;
    reminderCount: bigint;
    leadId: _LeadId;
    rating: bigint;
    rcStatus: _Status;
    quoteStatus: _Status;
    ownerChange: boolean;
    premiumAmount: bigint;
} {
    return {
        paymentStatus: to_candid_Status_n14(_uploadFile, _downloadFile, value.paymentStatus),
        pbStatus: to_candid_Status_n14(_uploadFile, _downloadFile, value.pbStatus),
        assignedAgent: value.assignedAgent,
        claimStatus: to_candid_Status_n14(_uploadFile, _downloadFile, value.claimStatus),
        policyStatus: to_candid_Status_n14(_uploadFile, _downloadFile, value.policyStatus),
        createdAt: value.createdAt,
        ncbPercent: value.ncbPercent,
        mobileNumber: value.mobileNumber,
        updatedAt: value.updatedAt,
        kycStatus: to_candid_Status_n14(_uploadFile, _downloadFile, value.kycStatus),
        reminderCount: value.reminderCount,
        leadId: value.leadId,
        rating: value.rating,
        rcStatus: to_candid_Status_n14(_uploadFile, _downloadFile, value.rcStatus),
        quoteStatus: to_candid_Status_n14(_uploadFile, _downloadFile, value.quoteStatus),
        ownerChange: value.ownerChange,
        premiumAmount: value.premiumAmount
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == Status.pending ? {
        pending: null
    } : value == Status.completed ? {
        completed: null
    } : value == Status.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    admin: null;
} | {
    agent: null;
} {
    return value == Role.admin ? {
        admin: null
    } : value == Role.agent ? {
        agent: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
