/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AgentId = Principal;
export interface Lead {
  'paymentStatus' : Status,
  'pbStatus' : Status,
  'assignedAgent' : AgentId,
  'claimStatus' : Status,
  'policyStatus' : Status,
  'createdAt' : Time,
  'ncbPercent' : bigint,
  'mobileNumber' : string,
  'updatedAt' : Time,
  'kycStatus' : Status,
  'reminderCount' : bigint,
  'leadId' : LeadId,
  'rating' : bigint,
  'rcStatus' : Status,
  'quoteStatus' : Status,
  'ownerChange' : boolean,
  'premiumAmount' : bigint,
}
export type LeadId = bigint;
export type Role = { 'admin' : null } |
  { 'agent' : null };
export type Status = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export type Time = bigint;
export interface User {
  'principal' : UserId,
  'name' : string,
  'role' : Role,
  'email' : string,
}
export type UserId = Principal;
export interface _SERVICE {
  'assignLead' : ActorMethod<[LeadId, AgentId], undefined>,
  'createLead' : ActorMethod<[string], LeadId>,
  'createUser' : ActorMethod<[UserId, string, Role, string], undefined>,
  'getAllLeads' : ActorMethod<[], Array<Lead>>,
  'getLead' : ActorMethod<[LeadId], Lead>,
  'getLeadsByAgent' : ActorMethod<[AgentId], Array<Lead>>,
  'getUser' : ActorMethod<[UserId], User>,
  'updateLead' : ActorMethod<[LeadId, Lead], undefined>,
  'updateLeadStatus' : ActorMethod<[LeadId, Status], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];