/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LeadId = IDL.Nat;
export const AgentId = IDL.Principal;
export const UserId = IDL.Principal;
export const Role = IDL.Variant({ 'admin' : IDL.Null, 'agent' : IDL.Null });
export const Status = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Time = IDL.Int;
export const Lead = IDL.Record({
  'paymentStatus' : Status,
  'pbStatus' : Status,
  'assignedAgent' : AgentId,
  'claimStatus' : Status,
  'policyStatus' : Status,
  'createdAt' : Time,
  'ncbPercent' : IDL.Nat,
  'mobileNumber' : IDL.Text,
  'updatedAt' : Time,
  'kycStatus' : Status,
  'reminderCount' : IDL.Nat,
  'leadId' : LeadId,
  'rating' : IDL.Nat,
  'rcStatus' : Status,
  'quoteStatus' : Status,
  'ownerChange' : IDL.Bool,
  'premiumAmount' : IDL.Nat,
});
export const User = IDL.Record({
  'principal' : UserId,
  'name' : IDL.Text,
  'role' : Role,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  'assignLead' : IDL.Func([LeadId, AgentId], [], []),
  'createLead' : IDL.Func([IDL.Text], [LeadId], []),
  'createUser' : IDL.Func([UserId, IDL.Text, Role, IDL.Text], [], []),
  'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getLead' : IDL.Func([LeadId], [Lead], ['query']),
  'getLeadsByAgent' : IDL.Func([AgentId], [IDL.Vec(Lead)], ['query']),
  'getUser' : IDL.Func([UserId], [User], ['query']),
  'updateLead' : IDL.Func([LeadId, Lead], [], []),
  'updateLeadStatus' : IDL.Func([LeadId, Status], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LeadId = IDL.Nat;
  const AgentId = IDL.Principal;
  const UserId = IDL.Principal;
  const Role = IDL.Variant({ 'admin' : IDL.Null, 'agent' : IDL.Null });
  const Status = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Time = IDL.Int;
  const Lead = IDL.Record({
    'paymentStatus' : Status,
    'pbStatus' : Status,
    'assignedAgent' : AgentId,
    'claimStatus' : Status,
    'policyStatus' : Status,
    'createdAt' : Time,
    'ncbPercent' : IDL.Nat,
    'mobileNumber' : IDL.Text,
    'updatedAt' : Time,
    'kycStatus' : Status,
    'reminderCount' : IDL.Nat,
    'leadId' : LeadId,
    'rating' : IDL.Nat,
    'rcStatus' : Status,
    'quoteStatus' : Status,
    'ownerChange' : IDL.Bool,
    'premiumAmount' : IDL.Nat,
  });
  const User = IDL.Record({
    'principal' : UserId,
    'name' : IDL.Text,
    'role' : Role,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    'assignLead' : IDL.Func([LeadId, AgentId], [], []),
    'createLead' : IDL.Func([IDL.Text], [LeadId], []),
    'createUser' : IDL.Func([UserId, IDL.Text, Role, IDL.Text], [], []),
    'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getLead' : IDL.Func([LeadId], [Lead], ['query']),
    'getLeadsByAgent' : IDL.Func([AgentId], [IDL.Vec(Lead)], ['query']),
    'getUser' : IDL.Func([UserId], [User], ['query']),
    'updateLead' : IDL.Func([LeadId, Lead], [], []),
    'updateLeadStatus' : IDL.Func([LeadId, Status], [], []),
  });
};

export const init = ({ IDL }) => { return []; };